version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: system_manager_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: system_manager
      TZ: UTC
      PGTZ: UTC
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=100'
      - '-c'
      - 'shared_buffers=256MB'
      - '-c'
      - 'effective_cache_size=768MB'
      - '-c'
      - 'maintenance_work_mem=64MB'
      - '-c'
      - 'checkpoint_completion_target=0.9'
      - '-c'
      - 'wal_buffers=7864kB'
      - '-c'
      - 'default_statistics_target=100'
      - '-c'
      - 'random_page_cost=1.1'
      - '-c'
      - 'effective_io_concurrency=200'

  pgadmin:
    image: dpage/pgadmin4
    container_name: system_manager_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
